### ISSUE TITLE
0x00ad is in two intervals

### ISSUE THREAD

**Issue by kuerbis** [joshuarubin/wcwidth9#2]
0x00ad is in the nonprint interval and in the ambiguous interval.

**Comment by joshuarubin** [comment]
hmm, not sure why it is marked as nonprintable, I'll have to look into it

**Comment by kuerbis** [comment]
Here it is not in the ambiguous range: http://www.cl.cam.ac.uk/%7Emgk25/ucs/wcwidth.c

**Comment by joshuarubin** [comment]
[UnicodeData.txt](http://ftp.unicode.org/Public/UNIDATA/UnicodeData.txt) lists it as category `Cf` (Other,Format). [EastAsianWidth.txt](http://ftp.unicode.org/Public/UNIDATA/EastAsianWidth.txt) lists it as ambiguous width. neovim lists it as ambiguous as well. So I think there is no question it should be marked as ambiguous.

I'm still trying to figure out if it should also be marked as non-printable...

**Comment by joshuarubin** [comment]
OK, after reading [this](http://archives.miloush.net/michkap/archive/2006/09/02/736881.html) I think it is appropriate to keep it marked as non-printable. Browsers do not render it AFAIK. It is intended to be a control character that indicates the place within a word that a line-break may be placed.
